task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox']

num_classes: 1
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ../dataset/hardneg_v1/images
    ann_file: ../dataset/hardneg_v1/annotations/instances_train_hardneg.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ../dataset/train/images
    ann_file: ../dataset/annotations_multibox_v2/instances_val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
